defaults:
  -
    scope:
       path: ""
       type: "posts"
    values:
       layout: "default"
       author: "Raphael Ho"
paginate: 5
paginate_path: "/page:num"
highlighter: pygment
encoding: utf-8